name: container

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/leb4r/trader-go

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read go version
        id: go-version
        run: |
          content=`cat ./.go-version`
          echo "::set-output name=content::$content"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to Container Registries
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GOVERSION=${{ steps.go-version.outputs.content }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
